# Form implementation generated from reading ui file 'VentanaSecundaria.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaSecundaria(object):
    def setupUi(self, VentanaSecundaria):
        VentanaSecundaria.setObjectName("VentanaSecundaria")
        VentanaSecundaria.resize(668, 311)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=VentanaSecundaria)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(VentanaSecundaria)
        QtCore.QMetaObject.connectSlotsByName(VentanaSecundaria)

    def retranslateUi(self, VentanaSecundaria):
        _translate = QtCore.QCoreApplication.translate
        VentanaSecundaria.setWindowTitle(_translate("VentanaSecundaria", "VentanaSecundaria"))
        self.label.setText(_translate("VentanaSecundaria", "Información Mascota"))
        self.label_2.setText(_translate("VentanaSecundaria", "datos de la mascota"))
        self.label_3.setText(_translate("VentanaSecundaria", "texto"))
        self.pushButton.setText(_translate("VentanaSecundaria", "OK"))
